### PR TITLE
Kl jobs

### PR DESCRIPTION
**Pull request by lewiskg**
Jobs page ready for review.

### CODE REVIEW

**Comment by Junochop** [comment]
viewed the files through codepen.  funny descriptions.  I did not find any issues.

**Comment by Junochop** [comment]
question...regarding the nav bar paths.   Should the nav paths be
                          ./index.html 
	                ../html/history.html
	                ../html/mission.html
	                ../html/employees.html
                        ../html/awards.html
	                ../html/jobs.html
	                ../html/store.html  ?  or 

                        ../index.html 
	                ../html/history.html
	                ../html/mission.html
	                ../html/employees.html
                        ../html/awards.html
	                ../html/jobs.html
	                ../html/store.html
	??

**Comment by hagansmith** [comment]
👍

**Comment by lewiskg** [comment]
Yep.  I'll change the ./index.html to ../index.html

**Comment by lewiskg** [comment]
Looks like mine already has ../index.html

**Pull request merged**
