### PR TITLE
Header styling

### PR DESCRIPTION
**Pull request by kstoops815**
Checkout header and footer styling. Let me know if anything needs to be changed.  Thanks!  Love to ya mutha!

### CODE REVIEW

**Comment by hagansmith** [comment]
this looks good, wondering about the active link showing as a different color or size. You decided to scrap that for now?

**Comment by kstoops815** [comment]
Crap...I forgot about that!  I will fix it and push it up again.  Thanks for reminding me!

**Comment by kstoops815** [comment]
Added styling to the nav links.

**Comment by lewiskg** [comment]
Great.  Nice pictures.

**Comment by Junochop** [comment]
Nice!!

**Comment by hagansmith** [comment]
👍

**Pull request merged**
