### PR TITLE
added footer context

### PR DESCRIPTION
**Pull request by kstoops815**

### CODE REVIEW

**Comment by lewiskg** [comment]
Thumbs up!  Juno caught a typo.

**Comment by Junochop** [comment]
Please check "thether" spelling @ copyright

**Comment by hagansmith** [comment]
good

**Comment by cmurnick** [comment]
👍

**Comment by kstoops815** [comment]
spelling corrected

**Comment by lewiskg** [comment]
Correction looks good.

**Comment by Junochop** [comment]
Looks good

**Pull request merged**
