### PR TITLE
adding my stuff

### PR DESCRIPTION
**Pull request by cmurnick**

### CODE REVIEW

**Comment by kstoops815** [comment]
Can you change the id "title" to title-history to prevent merge conflicts. Thanks!

**Comment by Junochop** [comment]
could you add a class tag to your img?

**Comment by Junochop** [comment]
thumbs up

**Comment by lewiskg** [comment]
I see the corrections.  Looks good.

**Review by kstoops815 — APPROVED** [review]
Looks good!

**Pull request merged**
